#!/bin/bash
echo `hostname`

cd $TASK_DIR
if [ -d "/usr/lib/matlab/R2013a" ]; then
    /usr/lib/matlab/R2013a/bin/matlab -nodisplay -r "remote_add_relevant_src_paths('$DATA_PATH');run_remote_job('$DATA_PATH');"
elif [ -d "/usr/lib/matlab/R2013b" ]; then 
    /usr/lib/matlab/R2013b/bin/matlab -nodisplay -r "remote_add_relevant_src_paths('$DATA_PATH');run_remote_job('$DATA_PATH');"
elif [ -d "/usr/lib/matlab/R2014a" ]; then 
    /usr/lib/matlab/R2014a/bin/matlab -nodisplay -r "remote_add_relevant_src_paths('$DATA_PATH');run_remote_job('$DATA_PATH');"
else
    echo -e 'No Matlab installations found.\n'
fi
