#!/bin/bash
echo `hostname`

cd $TASK_DIR

if [ "$(uname)" == "Darwin" ]; then
    matlab_version=$(greadlink -f $(which matlab) | ack -o "R[0-9]+[ab]+" | ack -o "[0-9]+");
else
    matlab_version=$(readlink -f $(which matlab) | grep -oP "R[0-9]+[ab]+" | grep -oP "[0-9]+");
fi

matlab_gt_2013=$(python -c "print $matlab_version >= 2013")

if [ "$matlab_gt_2013"  == "True" ]
then

    matlab -nodisplay -r "remote_add_relevant_src_paths('$DATA_PATH');run_remote_job('$DATA_PATH');exit;"

else

    echo -e "Matador: The only Matlab installation found is $matlab_version, which is too old."

fi
