#!/bin/bash
echo `hostname`

cd $TASK_DIR
source activate $CONDAENV
PYTHONPATH=$PYTHONPATH:$PYTHON_PATH_ADDITIONS

python -c "from pyena.src.core import run_remote_job;run_remote_job('$DATA_PATH');exit;"

